# Generated by Django 3.0.8 on 2020-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200710_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=250),
        ),
    ]
